version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "=== Checking pre-installed Terraform ==="
      - terraform --version || echo "Terraform not found, will install"
      - echo "=== Installation phase completed ==="

  pre_build:
    commands:
      - echo "=== Pre-build phase ==="
      - pwd && ls -la
      - echo 'project_name = "terraform-conformity-demo-v2"' > terraform.tfvars
      - echo 'conformity_region = "us-east-1"' >> terraform.tfvars
      - echo 'github_owner = "adusei2023"' >> terraform.tfvars
      - echo 'github_repo = "terraform-conformity-pipeline"' >> terraform.tfvars
      - echo 'github_branch = "main"' >> terraform.tfvars
      - echo 'aws_region = "us-east-1"' >> terraform.tfvars
      - echo 'conformity_api_key = "dummy"' >> terraform.tfvars
      - echo 'github_token = "dummy"' >> terraform.tfvars
      - echo 'github_webhook_secret = "dummy"' >> terraform.tfvars
      - terraform init

  build:
    commands:
      - terraform validate
      - terraform plan -out=tfplan
      - echo "Build completed successfully"

  post_build:
    commands:
      - echo "Pipeline completed at $(date)"

artifacts:
  files:
    - '**/*'
