version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "=== Installing Terraform ==="
      - yum update -y
      - yum install -y wget unzip
      - cd /tmp
      - wget https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip
      - unzip terraform_1.6.0_linux_amd64.zip
      - chmod +x terraform
      - mv terraform /usr/local/bin/
      - terraform --version

  pre_build:
    commands:
      - echo "=== Pre-build phase ==="
      - pwd && ls -la
      - find . -name "*.tf" -type f
      - echo "=== Navigating to terraform directory ==="
      - cd terraform || pwd
      - ls -la
      - echo "=== Creating terraform.tfvars ==="
      - echo 'aws_region = "us-east-1"' > terraform.tfvars
      - echo 'project_name = "terraform-conformity-demo-v2"' >> terraform.tfvars
      - echo 'conformity_region = "us-east-1"' >> terraform.tfvars
      - echo 'github_owner = "adusei2023"' >> terraform.tfvars
      - echo 'github_repo = "terraform-conformity-pipeline"' >> terraform.tfvars
      - echo 'github_branch = "main"' >> terraform.tfvars
      - echo 'conformity_api_key = "dummy"' >> terraform.tfvars
      - echo 'github_token = "dummy"' >> terraform.tfvars
      - echo 'github_webhook_secret = "dummy"' >> terraform.tfvars
      - terraform init

  build:
    commands:
      - echo "=== Build phase ==="
      - terraform validate
      - echo "=== Demo Security Scan ==="
      - echo "Starting Cloud Conformity Security Scan..."
      - echo "Configuration validated successfully"
      - echo "No critical security issues detected"
      - echo "Pipeline demonstration completed"

  post_build:
    commands:
      - echo "Pipeline completed successfully"

artifacts:
  files:
    - '**/*'
