# This Terraform configuration sets up a test environment with known security issues
version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - echo "=== Installing Terraform ==="
      - echo "Checking current directory and available tools..."
      - pwd
      - which wget || which curl
      - echo "Downloading Terraform..."
      - curl -fsSL https://releases.hashicorp.com/terraform/1.6.0/terraform_1.6.0_linux_amd64.zip -o terraform_1.6.0_linux_amd64.zip
      - echo "Verifying download..."
      - ls -la terraform_1.6.0_linux_amd64.zip
      - echo "Extracting Terraform..."
      - unzip terraform_1.6.0_linux_amd64.zip
      - echo "Installing Terraform..."
      - chmod +x terraform
      - mv terraform /usr/local/bin/
      - echo "Verifying Terraform installation..."
      - terraform --version
      - echo "=== Terraform installed successfully ==="

  pre_build:
    commands:
      - echo "=== Pre-build phase started ==="
      - echo "Current directory is $(pwd)"
      - echo "Directory contents:"
      - ls -la
      - echo "=== Navigating to terraform directory ==="
      - cd terraform
      - echo "Terraform directory contents:"
      - ls -la
      - echo "=== Creating terraform.tfvars ==="
      - echo 'project_name = "terraform-conformity-demo-v2"' > terraform.tfvars
      - echo 'conformity_region = "us-east-1"' >> terraform.tfvars
      - echo 'github_owner = "adusei2023"' >> terraform.tfvars
      - echo 'github_repo = "terraform-conformity-pipeline"' >> terraform.tfvars
      - echo 'github_branch = "main"' >> terraform.tfvars
      - echo 'aws_region = "us-east-1"' >> terraform.tfvars
      - echo 'conformity_api_key = "dummy-will-be-overridden"' >> terraform.tfvars
      - echo 'github_token = "dummy-will-be-overridden"' >> terraform.tfvars
      - echo 'github_webhook_secret = "dummy-will-be-overridden"' >> terraform.tfvars
      - echo "=== terraform.tfvars created ==="
      - cat terraform.tfvars
      - echo "=== Running terraform init ==="
      - terraform init

  build:
    commands:
      - echo "=== Build phase started ==="
      - echo "=== Running terraform validate ==="
      - terraform validate
      - echo "=== Running terraform plan ==="
      - terraform plan -out=tfplan
      - echo "=== Terraform plan completed successfully ==="
      - echo "=== Security scan completed (demo) ==="

  post_build:
    commands:
      - echo "=== Post-build phase ==="
      - echo "Build completed successfully at $(date)"

artifacts:
  files:
    - '**/*'